import { defineType, defineField } from 'sanity'

export const homepageType = defineType({
  name: 'homepage',
  title: "Page d'accueil",
  type: 'document',
  groups: [
    { name: 'hero', title: '🎬 Section principale' },
    { name: 'about', title: '📖 À propos' },
    { name: 'philosophy', title: '🌿 Philosophie' },
    { name: 'featured', title: '🖼️ Mise en avant' },
    { name: 'services', title: '📋 Nos services' },
  ],
  fields: [
    // Hero
    defineField({
      name: 'heroImage',
      title: 'Photo de fond',
      type: 'image',
      group: 'hero',
      options: { hotspot: true },
      description: "Photo affichée en transparence derrière le titre principal. Si vide, une photo par défaut est utilisée.",
    }),
    defineField({
      name: 'heroTagline',
      title: 'Ligne au-dessus du titre',
      type: 'string',
      group: 'hero',
      description: "Petite ligne discrète au-dessus du titre. Ex: École de Danse · Saint-Michel-Chef-Chef",
    }),
    defineField({
      name: 'heroTitle',
      title: 'Titre principal',
      type: 'string',
      group: 'hero',
      description: "Le grand titre affiché sur la page d'accueil. Ex: La danse, une passion à partager.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroDescription',
      title: 'Description sous le titre',
      type: 'text',
      rows: 3,
      group: 'hero',
      description: "Phrase courte qui présente l'école.",
    }),
    // About
    defineField({
      name: 'aboutTitle',
      title: "Phrase de présentation",
      type: 'text',
      rows: 3,
      group: 'about',
      description: "Grande phrase qui résume l'esprit de l'association. Affichée dans la section de présentation.",
    }),
    // Philosophy
    defineField({
      name: 'philosophyTitle',
      title: 'Titre de la section',
      type: 'string',
      group: 'philosophy',
      description: "Ex: La danse comme art de vivre.",
    }),
    defineField({
      name: 'philosophyImage',
      title: 'Photo',
      type: 'image',
      group: 'philosophy',
      options: { hotspot: true },
      description: "Photo affichée à gauche du texte. Si vide, une photo par défaut est utilisée.",
    }),
    defineField({
      name: 'philosophyBlock1Label',
      title: 'Bloc 1 — Titre court',
      type: 'string',
      group: 'philosophy',
      description: "Titre en majuscules. Ex: NOTRE HISTOIRE",
    }),
    defineField({
      name: 'philosophyBlock1Text',
      title: 'Bloc 1 — Texte',
      type: 'text',
      rows: 4,
      group: 'philosophy',
    }),
    defineField({
      name: 'philosophyBlock2Label',
      title: 'Bloc 2 — Titre court',
      type: 'string',
      group: 'philosophy',
      description: "Titre en majuscules. Ex: NOTRE ENGAGEMENT",
    }),
    defineField({
      name: 'philosophyBlock2Text',
      title: 'Bloc 2 — Texte',
      type: 'text',
      rows: 4,
      group: 'philosophy',
    }),
    // Featured
    defineField({
      name: 'featuredImage',
      title: 'Grande photo',
      type: 'image',
      group: 'featured',
      options: { hotspot: true },
      description: "Photo panoramique affichée en pleine largeur. Si vide, une photo par défaut est utilisée.",
    }),
    defineField({
      name: 'featuredSectionLabel',
      title: 'Titre court au-dessus du texte',
      type: 'string',
      group: 'featured',
      description: "Ex: NOTRE APPROCHE",
    }),
    defineField({
      name: 'featuredVideoDescription',
      title: 'Texte descriptif',
      type: 'text',
      rows: 3,
      group: 'featured',
      description: "Texte affiché sur la photo en bas à gauche.",
    }),
    // Services
    defineField({
      name: 'servicesSectionTitle',
      title: 'Titre de la section',
      type: 'string',
      group: 'services',
      description: "Ex: Ce que nous proposons",
    }),
    defineField({
      name: 'servicesSectionSubtitle',
      title: 'Sous-titre',
      type: 'string',
      group: 'services',
      description: "Ex: Cours hebdomadaires & stages ponctuels",
    }),
    defineField({
      name: 'servicesCard1Image',
      title: 'Carte Disciplines — Photo',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
      description: "Photo de la carte 'Nos Disciplines'. Si vide, une photo par défaut est utilisée.",
    }),
    defineField({
      name: 'servicesCard1Description',
      title: 'Carte Disciplines — Texte',
      type: 'text',
      rows: 2,
      group: 'services',
    }),
    defineField({
      name: 'servicesCard2Image',
      title: 'Carte Cours & Stages — Photo',
      type: 'image',
      group: 'services',
      options: { hotspot: true },
      description: "Photo de la carte 'Cours & Stages'. Si vide, une photo par défaut est utilisée.",
    }),
    defineField({
      name: 'servicesCard2Description',
      title: 'Carte Cours & Stages — Texte',
      type: 'text',
      rows: 2,
      group: 'services',
    }),
  ],
  preview: {
    prepare() {
      return { title: "Page d'accueil" }
    },
  },
})
